### ISSUE TITLE
Impossible to handle errors from transaction

### ISSUE THREAD

**Issue by Daimon-EuDaimon** [Yamanlk/transactional-prisma#1]
When an error occurs in a transaction, it is rolled back and the object `{ Symbol(prisma.client.extension.rollback): true }` is thrown. I'd like to receive the error that caused the transaction to be rolled back.

**Comment by Daimon-EuDaimon** [comment]
I propose this solution,
on src/flat-transaction.ts:48 replace
`return tx;` with
`return tx.catch((e: any) => e[Symbol.for("prisma.client.extension.rollback")] ? undefined : tx);`

**Comment by bytadaniel** [comment]
Hey! I have the same problem. There are some issues with handling errors..

**Comment by Yamanlk** [comment]
I'll look into it

**Comment by Yamanlk** [comment]
Fixed in `1.1.1`
